Repository ironcore-dev/machine-controller-manager-provider-ironcore, pull requests merged in 2023-03, with the labels that each got.

#92 Bump MCM and onmetal-api
  cmd/machine-controller/main.go
  go.mod
  go.sum
  pkg/onmetal/get_machine_status.go
  pkg/onmetal/suite_test.go
Labels: enhancement, size/M, provider

#93 Add GH `clean` workflow
  .github/release-drafter.yml
  .github/workflows/clean.yml
  go.sum
  hack/check.sh
Labels: size/M, chore

#97 Improve test coverage of `ListMachines`
  pkg/onmetal/list_machines.go
  pkg/onmetal/list_machines_test.go
Labels: enhancement, size/M, provider

#94 Add `dnsServers` to `ProviderSpec`
  pkg/api/v1alpha1/provider.go
  pkg/api/validation/validation.go
  pkg/api/validation/validation_test.go
  pkg/ignition/config.go
  pkg/ignition/template.yaml
  pkg/internal/providerspec.go
  pkg/onmetal/create_machine.go
  pkg/onmetal/create_machine_test.go
Labels: enhancement, size/L, provider

#101 Fix `ProviderSpec` validation and validation tests
  pkg/api/validation/validation.go
  pkg/api/validation/validation_test.go
Labels: bug, size/S

#103 Use `map[string]interface{}` for `SampleProviderSpec` and `SampleIgnition`
  pkg/internal/providerspec.go
  pkg/onmetal/create_machine_test.go
  pkg/onmetal/delete_machine_test.go
  pkg/onmetal/get_machine_status_test.go
  pkg/onmetal/list_machines_test.go
  pkg/onmetal/suite_test.go
  pkg/onmetal/testing/testing.go
Labels: enhancement, size/L, provider

#109 Remove forked dependency to MCM
  go.mod
  go.sum
Labels: size/S, chore
