Repository ironcore-dev/machine-controller-manager-provider-ironcore, pull requests merged in 2023-02, with the labels that each got.

#70 Add `onmetal-kubeconfig` flag
  cmd/machine-controller/main.go
  go.sum
  kubernetes/deployment.yaml
  pkg/api/validation/validation.go
  pkg/onmetal/create_machine.go
  pkg/onmetal/create_machine_test.go
  pkg/onmetal/delete_machine.go
  pkg/onmetal/driver.go
  pkg/onmetal/get_machine_status.go
  pkg/onmetal/list_machines.go
  pkg/onmetal/suite_test.go
Labels: enhancement, size/L, provider

#68 Validation for provider spec and unit testing.
  pkg/api/validation/validation.go
  pkg/api/validation/validation_suite_test.go
  pkg/api/validation/validation_test.go
Labels: enhancement, size/L

#71 Bump `onmetal-api` and `controller-utils`
  go.mod
  go.sum
  pkg/onmetal/create_machine.go
  pkg/onmetal/create_machine_test.go
  pkg/onmetal/suite_test.go
Labels: enhancement, size/M, provider

#74 Fix `Volume` and `NetworkInterface` naming
  pkg/onmetal/create_machine.go
  pkg/onmetal/create_machine_test.go
Labels: bug, size/XS, provider

#75 Add missing `prefixLength` to IP allocation
  pkg/onmetal/create_machine.go
  pkg/onmetal/create_machine_test.go
Labels: bug, size/XS, provider

#76 Fix `NetworkInterface` `Prefix` allocation
  pkg/onmetal/create_machine.go
  pkg/onmetal/create_machine_test.go
Labels: bug, size/XS, provider

#77 Add default nameserver to `Machine` ignition configuration
  pkg/ignition/template.yaml
  pkg/onmetal/create_machine_test.go
Labels: enhancement, size/XS, provider
