Repository ironcore-dev/machine-controller-manager-provider-ironcore, pull requests merged in 2023-11, with the labels that each got.

#271 Add `golangci-lint` installation to `Makefile`
  Makefile
Labels: size/S

#272 Rename project to `machine-controller-manager-provider-ironcore`
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/publish-docker.yml
  CODEOWNERS
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  cmd/machine-controller/main.go
  go.mod
  go.sum
  hack/api-reference/config.json
  kubernetes/deployment.yaml
  kubernetes/machine-class.yaml
  kubernetes/secret.yaml
  pkg/api/v1alpha1/provider.go
  pkg/api/validation/validation.go
  pkg/api/validation/validation_test.go
  pkg/ignition/template.yaml
  pkg/ironcore/create_machine.go
  pkg/ironcore/create_machine_test.go
  pkg/ironcore/delete_machine.go
  pkg/ironcore/delete_machine_test.go
  pkg/ironcore/driver.go
  pkg/ironcore/get_machine_status.go
  pkg/ironcore/get_machine_status_test.go
  pkg/ironcore/get_volume_ids.go
  pkg/ironcore/get_volume_ids_test.go
  pkg/ironcore/list_machines.go
  pkg/ironcore/list_machines_test.go
  pkg/ironcore/suite_test.go
  pkg/ironcore/testing/testing.go
Labels: documentation, enhancement, size/L, breaking, minor

#276 Add `breaking` category and label in release drafter
  .github/release-drafter.yml
Labels: enhancement, size/XS

#277 Make project REUSE compliant
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  Makefile
  README.md
  cmd/machine-controller/main.go
  hack/api-reference/template/tools.go
  hack/license-header.txt
  pkg/api/v1alpha1/doc.go
  pkg/api/v1alpha1/provider.go
  pkg/api/validation/validation.go
  pkg/api/validation/validation_suite_test.go
  pkg/api/validation/validation_test.go
  pkg/ignition/config.go
  pkg/ironcore/create_machine.go
  pkg/ironcore/create_machine_test.go
  pkg/ironcore/delete_machine.go
  pkg/ironcore/delete_machine_test.go
  pkg/ironcore/driver.go
  pkg/ironcore/get_machine_status.go
  pkg/ironcore/get_machine_status_test.go
  pkg/ironcore/get_volume_ids.go
  pkg/ironcore/get_volume_ids_test.go
  pkg/ironcore/list_machines.go
  pkg/ironcore/list_machines_test.go
  pkg/ironcore/suite_test.go
  pkg/ironcore/testing/testing.go
Labels: documentation, enhancement, size/L, provider

#275 Fix wrong CSI driver name reference
  README.md
  cmd/machine-controller/main.go
  pkg/ironcore/driver.go
  pkg/ironcore/get_volume_ids.go
  pkg/ironcore/get_volume_ids_test.go
  pkg/ironcore/suite_test.go
Labels: bug, documentation, size/S, provider
